### ISSUE TITLE
Thank you for working on the color correction

### ISSUE THREAD

**Issue by nils** [jackw01/led-control#10]
Hi @jackw01,

I just wanted to let you know that your recent changes (commit https://github.com/jackw01/led-control/commit/bc3e76fc16f1dea6363582ad40b22fa55e816d7f) concerning color correction are appreciated!

For me, a white gradient has changed from this:
![image](https://user-images.githubusercontent.com/12449/105637223-9ab58b80-5e6c-11eb-9799-9f15b35975ad.png)
to this on the most recent version:
![image](https://user-images.githubusercontent.com/12449/105637231-a1440300-5e6c-11eb-8d75-dad48c9c8893.png)

I'm using `--led_color_correction #FFFFFF` and color temperature 6600K by the way, I think that's better for white gradients, right?

However, depending on the pattern, the color correction might still be wanted... Maybe the pattern could control that itself by returning new color formats in addition to `rgb` and `hsv` (e.g. `rgbraw` and `hsvraw`?) where the `*raw` types skip color correction?

Best Regards,
Nils

**Comment by jackw01** [comment]
Are you using an RGBW LED strip? If you are, the color correction and color temperature will not affect how white looks since they are applied to the RGB channels only after the white pixel value is calculated.

**Comment by nils** [comment]
Thanks for the clarification! Yes I'm indeed using an SK6812 RGBW strip. 

Good to know that white colors are not affected at all in this case 👍 So that's what you fixed in https://github.com/jackw01/led-control/commit/bc3e76fc16f1dea6363582ad40b22fa55e816d7f!
