### ISSUE TITLE
Does Not work now

### ISSUE THREAD

**Issue by CALPARDO** [jackw01/led-control#12]
Yesterday it worked really fine but today under the same conditions (I'm using GPIO 18 and all the default values except led count(120)), it does not work. My power supply is [this](https://urun.n11.com/adaptor-ve-cevirici/5-volt-10-amper-metal-kasa-adaptor-5v-10a-P453942041). In addition, I can use web UI and everything looks alright!
EDIT: I'm using pi zero with the Raspbian Lite OS
EDIT: I also tried by using arduino and it works but stopped working with raspberry pi

**Comment by ascheier** [comment]
I think I am having the same problem. Do you remember what fixed it?
