### ISSUE TITLE
Question: endpoint to reset cycle/counter

### ISSUE THREAD

**Issue by javl** [jackw01/led-control#17]
Thank you for this great tool.
I've added a webpage to use as a simple controller, with buttons that use GET requests to so I can easily switch between specific settings. For example: Button A might set the brightness to 0.2, speed to 0.1 and select the 'fire' color palette, while button B will set the brightness to 1.0, speed to 1.0 and enable a custom movement pattern.
This works great, and by sending the same GET request to multiple IP addresses I can control a couple of Raspberry Pi's at the same time.

The only problem I have is the cycle on the Pi's not being in sync. When I press button B to start a wiping movement on all Pi's they will switch to the pattern at (pretty much) the same time, but the position might be different as their current cycle positions are not the same.

I've been checking the code, but it doesn't seem to be an endpoint to reset the cycle, or am I missing something? If there isn't, do you have any suggestions on how to implement this?

(I hope my question is clear, feel free to let me know if it isn't).

**Comment by jackw01** [comment]
Didn't have time to test it, but this should work. Just send a request to `/resettimer`.

**Comment by javl** [comment]
Thanks for the quick answer and solution! I don't have access to the Pi's at the moment, but I'll let you know as soon as I'm able to test this.

**Comment by javl** [comment]
Just tested the update with 3 devices and it works great! Thanks again

**Comment by Fitipalek** [comment]
> Thank you for this great tool. I've added a webpage to use as a simple controller, with buttons that use GET requests to so I can easily switch between specific settings. For example: Button A might set the brightness to 0.2, speed to 0.1 and select the 'fire' color palette, while button B will set the brightness to 1.0, speed to 1.0 and enable a custom movement pattern. This works great, and by sending the same GET request to multiple IP addresses I can control a couple of Raspberry Pi's at the same time.
> 
> The only problem I have is the cycle on the Pi's not being in sync. When I press button B to start a wiping movement on all Pi's they will switch to the pattern at (pretty much) the same time, but the position might be different as their current cycle positions are not the same.
> 
> I've been checking the code, but it doesn't seem to be an endpoint to reset the cycle, or am I missing something? If there isn't, do you have any suggestions on how to implement this?
> 
> (I hope my question is clear, feel free to let me know if it isn't).

Can you give me an example of this GET request on another pi ?

Tkanks a lot

**Comment by javl** [comment]
hi @Fitipalek 

This isn't the most sophisticated way to do things, but it worked for the quick fix I needed. In my case I have 5 devices I wanted to sync, so I added a button in HTML:

        <button onclick="sync()">Sync</button>

Then in the javascript I defined a list of IP addresses for all my devices (I made them static in the router so they never change):

    const endpoints = [
        'http://192.168.1.201',
        'http://192.168.1.202',
        'http://192.168.1.203',
        'http://192.168.1.204',
        'http://192.168.1.205',
    ];

Lastly, the ```sync()``` function simply iterates over this list and requests the resettimer endpoint from all of them. Technically there might be a small delay between the calls, but in practise this seems to work fine and you can always hit the sync button again.

    function sync(){
        for (let i=0; i<endpoints.length;i++) {
            fetch(`${endpoints[i]}/resettimer`)
        }
    }

(Fetch is a command build into modern browsers, and we're ignoring whatever it might return)

**Comment by Javi** [comment]
I don't, but you probably didn't mean me ;)

**Comment by Fitipalek** [comment]
> I don't, but you probably didn't mean me ;)

sorry :)

**Comment by javl** [comment]
@Fitipalek I haven't used it but judging by the code [here](https://github.com/jackw01/led-control/blob/b723aa7d0270c974ba78d55e472e2784a7b82c99/ledcontrol/animationcontroller.py#L168) you need to send it a json object with the values you want to change, something like:

```
{
'setting1': 'value1',
'setting2': 'value2'
}
```

**Comment by Fitipalek** [comment]
@javl I found in java this piece of code:

`async set(path, value) {
    _.set(this.settings, path, value);
    console.log('Store set:', path, value);
    const delta = {};
    _.set(delta, path, value);
    await axios.post('/updatesettings', delta);
  }
`

when i run it like this : 
`async set(path, value) {
    _.set(this.settings, path, value);
    console.log('Store set:', path, value);
     const delta = {};
    _.set(delta, path, value);
    //fetch('http://10.23.24.12:8001/updatesettings',delta);
    axios.post('http://10.23.24.13:8001/updatesettings',delta);
    axios.post('http://10.23.24.12:8001/updatesettings',delta);
 }
`
it is working for local raspberry but not for the other
when i use postman tool from chrome and send post request, that way i can control both raspberries

Is there something what is blocking post requests but not get requests ?

Thanks :)

**Comment by Fitipalek** [comment]
I edited this piece of code in Python on one of the rasperries and now it is working for me :)
``
    @app.post('/updatesettings')
    def update_settings():
        'Update settings'
        new_settings = request.json
        x = requests.post('http://10.23.24.12:8001/updatesettings', json = new_settings )
        controller.update_settings(new_settings)
        return jsonify(result='')
``

Thanks :)

**Comment by jackw01** [comment]
> @javl I found in java this piece of code:
> 
> ```
>    async set(path, value) {
>        _.set(this.settings, path, value);
>        console.log('Store set:', path, value);
>        const delta = {};
>        _.set(delta, path, value);
>        await axios.post('/updatesettings', delta);
>     }
> ```
> 
> when i run it like this :
> 
> ```
>    async set(path, value) {
>        _.set(this.settings, path, value);
>       console.log('Store set:', path, value);
>       const delta = {};
>       _.set(delta, path, value);
>       //fetch('http://10.23.24.12:8001/updatesettings',delta);
>       axios.post('http://10.23.24.13:8001/updatesettings',delta);
>       axios.post('http://10.23.24.12:8001/updatesettings',delta);
>    }
> ```
> 
> it is working for local raspberry but not for the other when i use postman tool from chrome and send post request, that way i can control both raspberries
> 
> Is there something what is blocking post requests but not get requests ?
> 
> Thanks :)

This doesn't work because you can't send cross-origin requests from Javascript code running inside of a website. This is a security feature. If you were to send these POST requests from Javascript code running in Node.js or from a program written in any other language, they would work.

**Comment by javl** [comment]
@jackw01 Not necessarily. By default cross-origin requests are not allowed, but I've added flask-cors in my fork to allow these requests.
https://github.com/javl/led-control/commit/489ec918962a73d4baec8ca6261fb495005d37c2

Note: opening up your server this way can be a very bad idea. Imagine someone turning on all of your LEDs to full brightness while your power supply is not rated for full power / long durations of such power delivery. 
I needed this so I can control my setup from a phone, but the router I'm using is NOT connected to the internet, it's just for a local network.
