### ISSUE TITLE
Current estimation in the README - what's this based on?

### ISSUE THREAD

**Issue by ohthehugemanatee** [jackw01/led-control#21]
I was calculating my power needs based on the current estimate in the README (4A to drive 150 LEDs)... but I noticed that when I buy LED strips, the listed power consumption is about double that. For example, [this 144 LED SK6812 strip](https://www.ledlightinghut.com/144-sk6812-4-in-1-rgbw-led-strip.html) which says it draws 34.5W (= about 7A). 

What's the 4A number based on? I want to be careful here, as this has a big impact on wire gauge, fuses, etc.

**Comment by jackw01** [comment]
In this case, their 34.5W estimate is based on the standard ~50mA per pixel current consumption, so 7A for 144 LEDs is correct for RGB LED strips with up to 3 LEDs per pixel being turned on at a time. 

For RGBW, no more than the equivalent of 2 of the 4 LEDs per pixel will ever be completely turned on at the same time (at least with LEDControl). From my testing, the LEDs in RGBW strips also seem to draw much less current than the LEDs in RGB strips. Here's the exact measurements I got from one strip of 150 SK6812 RGBW LEDs:

- White 100% brightness: 2.29A 4.80V (15.3mA per pixel)
- White 50% brightness: 1.58A 4.85V (10.5mA per pixel)
- Red 100% brightness: 1.64A 4.83V (10.9mA per pixel)
- Yellow 100% brightness: 2.43A 4.78V (16.2mA per pixel)
- Green 100% brightness: 1.16A 4.86V (7.7mA per pixel)
- Cyan 100% brightness: 2.30A 4.79V (15.3mA per pixel)
- Blue 100% brightness: 1.63A 4.83V (10.9mA per pixel)
- Magenta 100% brightness: 2.60A 4.76V (17.3mA per pixel)

With LEDControl's RGB/HSV to RGBW conversion method, desaturated colors will always draw less current than fully saturated colors or pure white. The voltages were measured at the middle of the LED strip to account for voltage drop and give an idea of the voltages the LEDs actually receive.
