### ISSUE TITLE
Ability to add custom secondary patterns

### ISSUE THREAD

**Issue by ohthehugemanatee** [jackw01/led-control#22]
Is there a reason there's no field for adding secondary patterns? I need to do this for my project, and would be happy to do it in a way that creates a patch for you.... but I'm worried that there may be a good reason you didn't add that already.

**Comment by ohthehugemanatee** [comment]
I'll give you my use case and you let me know what you think:

I'm using this project to control arrays of LED strips for a stage show. A central raspberry PI issues http calls to led-control running on a handful of pi-zeros in various places around the stage. Each pi zero controls its own strips; ie one pi zero controls the main backdrop, another one controls the lights on the piano, and another controls the long strip along the edge of the stage.  Here are the custom secondary patterns that I'm finding I want to implement:

- fade in/out. Start from whatever the previous state was, and in/decrement the `V` value to zero.
- Wipe in/out. Start from the previous state, and illuminate one pixel at a time along the length of the strip. Also needs a reversed version.
- Wipe in/out from center. Same as above, but symmetrical from the center of the `X` values. Also needs a vertical version.
- One off effects:
  - "Flash" to full brightness and slowly fade out
  - Shoot a single "bubble" of color across a blacked out strip.

Some of them I can imagine being generally useful, like fade or wipe. Others are totally idiosyncratic to my own situation.

You can  implement anything as a primary pattern, of course, but it gets pretty ugly. Fade, for example, would need a specific primary pattern specified as a second function, so the primary pattern can continue moving during the fade. This is exactly how primary/secondary patterns work already, but crammed into the one text field.

For now I'll submit individual PRs with the ones that seem generally useful. Let me know if you think other users might want to add their own secondaries and I'll figure out the UI stuff.

**Comment by jackw01** [comment]
First of all, you really should look at DMX, which is a very simple communication protocol designed specifically for your application (distributed real-time control of stage lighting). I currently have sACN (DMX via UDP) support built in, and this provides reasonably low latency (good enough for real-time music visualization) for remote control over ethernet or WiFi. With this, you can run a program like [LedFx](https://github.com/LedFx/LedFx) on your central computer which can control multiple client devices on the same network. LEDControl provides the benefit of being able to drive RGBW LEDs with RGB-only data sent over DMX.

I think some of these features (one-off secondary patterns that need to be triggered somehow) are outside the scope of implementing inside LEDControl itself, but there are probably other open-source DMX or sACN control projects that have this functionality already.

I would gladly accept pull requests improving DMX support, such as by adding support for hardware DMX interfaces or a DMX sender mode that allows LEDControl to stream data to other DMX devices to mirror or extend its display.
