### ISSUE TITLE
New Raspi Zero 2 Doesn't Work

### ISSUE THREAD

**Issue by ev5unleash** [jackw01/led-control#26]
Just tested led-control on the new Raspi Zero 2 and there doesn't seem to be a driver to support the GPIO pins. I can provide more verbose error messages if you would like.

**Comment by jackw01** [comment]
Try rebuilding with the latest changes (make sure the git submodule gets updated) and it should work. Any further Pi Zero 2 hardware compatibility issues should be tested with the example code [here](https://github.com/jgarff/rpi_ws281x) and reported on that repository.
