### ISSUE TITLE
Installation not working

### ISSUE THREAD

**Issue by ascheier** [jackw01/led-control#34]
I'm very new to LEDs to please bear with me. I have a raspberry pi 3B+ running python 3.7.4 and when I try to install this, I always get the same error code at the same step.
When I type `git checkout tags/v2.0.0`
I always get the error: `fatal: not a git repository (or any of the parent directories): .git`
Any help is greatly appreciated.

**Comment by jackw01** [comment]
The order of instructions in the readme was wrong, run ``cd led-control` before checking out v2.0.0.

**Comment by ascheier** [comment]
I thought I tried that earlier but I just tried it again and it worked. Thanks.
