### ISSUE TITLE
Random Lights

### ISSUE THREAD

**Issue by ascheier** [jackw01/led-control#36]
Well... I did have it working but I did something to my raspberry pi that required me to reinstall the OS. Anyway... I reinstalled the packages, following the READ ME and on the raspberry pi, it looks like it is working as expected. The lights, however, are not working. The first 6 LEDs are all different colors and the rest are off.
![IMG_8436](https://user-images.githubusercontent.com/63080605/158436789-7bdb0e1a-9bcc-4e2c-b38e-750c159d8589.jpg)
.

**Comment by ascheier** [comment]
I fixed it. This could also fix an issue if people see the web interface but there are no lights on. Heres how I did it:
`sudo nano /boot/config.txt`
Change `# Enable audio (loads snd_bcm2835)
dtparam=audio=on`
to `# Enable audio (loads snd_bcm2835)
#dtparam=audio=on`

@jackw01 , I would consider mentioning this in the software setup section of the README.

**Comment by ChrK2017** [comment]
Had the same problem, and now it works! Thanks!
