### ISSUE TITLE
How many LED's with 1 data pin

### ISSUE THREAD

**Issue by xnathan97** [jackw01/led-control#42]
Hi there, it's a great application. thx! 

Do you know, how many LED's I can control with 1 data pin from my raspberry? 

Thx for every answer!

**Comment by jackw01** [comment]
Depends on what raspberry pi mode, whether RGB or RGBW LEDs are used, and the minimum required framerate.

**Comment by xnathan97** [comment]
I can control 1500 RGB LED's with a RPi 3B+. It's awsome
