### ISSUE TITLE
Support 6 LEDs-per-pixel (24v strips)

### ISSUE THREAD

**Issue by ohthehugemanatee** [jackw01/led-control#46]
24v SK6812 strips commonly use 6 LEDs per pixel... but I can't figure out the pixel order for those 6 LEDs, and this tool only supports RGB/W variations. Is this a limitation of the underlying library?

**Comment by jackw01** [comment]
From what I can tell, these LED strips use the UCS2904 driver chip which is fully compatible with SK6812 and has four outputs (red, green, blue, and white). Each chip drives 6 LEDs in series to make use of the higher voltage (3 in series for a 12V strip) - the LEDs are not individually controlled and are addressable in groups of 6 (or 3).
